### ISSUE TITLE
replace ssdp-js with node-ssdp

### ISSUE THREAD

**Issue by grunjol** [grunjol/dlnacasts#2]
https://github.com/feross/webtorrent-desktop/issues/375

**Comment by feross** [comment]
Hey @grunjol, any progress on this?

**Comment by grunjol** [comment]
@feross will be working on it tomorrow. (this month was very busy).

**Comment by feross** [comment]
Cool, totally understand! Was busy for me too. I had two conferences in Germany, got sick, and finally got caught up on 100s of PRs and issues for all my GitHub projects :)

About to release WebTorrent v0.4!

**Comment by grunjol** [comment]
Code migrated to https://github.com/diversario/node-ssdp

**Comment by grunjol** [comment]
Released in 0.1.0

**Comment by grunjol** [comment]
@feross we can integrate it in webtorrent-desktop, API remains the same, no code change needed

**Comment by feross** [comment]
Nice -- will update.
